# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
#   namespace: mega
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ""
#   resources:
#     requests:
#       storage: 5Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mega
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
